# Generated by Django 4.2.2 on 2023-06-25 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("kaplancloudapp", "0016_add_uuid_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectWebHook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.URLField()),
                ("header", models.JSONField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kaplancloudapp.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectFileWebHook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.URLField()),
                ("header", models.JSONField()),
                (
                    "project_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kaplancloudapp.projectfile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
