# Generated by Django 3.2.10 on 2021-12-31 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaplancloudapp', '0004_auto_20211216_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationmemory',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kaplancloudapp.client'),
        ),
    ]
