# Generated by Django 3.2.11 on 2022-02-07 19:30

from django.db import migrations, models

def set_project_and_project_file_status(apps, schema_editor):
    Project = apps.get_model('kaplancloudapp', 'Project')
    for project in Project.objects.all():
        project.status = 4
        project.save()

    ProjectFile = apps.get_model('kaplancloudapp', 'ProjectFile')
    for project_file in ProjectFile.objects.all():
        project_file.status = 4
        project_file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kaplancloudapp', '0005_translationmemory_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Error'), (0, 'Preparing'), (1, 'Ready for Analysis'), (2, 'Analyzing'), (3, 'Ready for Translation'), (4, 'In Translation'), (5, 'In Review'), (6, 'Completed'), (7, 'Delivered')], default=0),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Error'), (0, 'Preparing'), (1, 'Ready for Analysis'), (2, 'Analyzing'), (3, 'Ready for Translation'), (4, 'In Translation'), (5, 'In Review'), (6, 'Completed'), (7, 'Delivered')], default=0),
        ),
        migrations.RunPython(set_project_and_project_file_status, migrations.RunPython.noop)
    ]
