# Generated by Django 3.2.12 on 2022-03-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaplancloudapp', '0012_projectreferencefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
