# Generated by Django 3.2.12 on 2022-03-22 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaplancloudapp', '0013_segment_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPreprocessingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('will_pretranslate', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaplancloudapp.project')),
            ],
        ),
    ]
