# Generated by Django 4.2.2 on 2023-07-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaplancloudapp', '0016_add_uuid_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languageprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='languageprofile',
            name='iso_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
