# Generated by Django 3.2.11 on 2022-01-30 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kaplancloudaccounts.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=kaplancloudaccounts.utils.generate_random_token, max_length=8, unique=True)),
                ('user_type', models.IntegerField(choices=[(0, 'Translator'), (1, 'PM')], default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
