version: "3.9"

networks:
  customnetwork:
    external: true
    name: ${NETWORK_NAME:-nginx-proxy}

volumes:
  staticfiles:
    name: ${PROJECT_NAME:-kaplan-cloud}_staticfiles

services:
  db:
    image: postgres
    container_name: ${PROJECT_NAME:-kaplan-cloud}_db
    volumes:
      - ./db/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432
    restart: unless-stopped
  app:
    image: kaplanpro/cloud
    container_name: ${PROJECT_NAME:-kaplan-cloud}_app
    volumes:
      - ./app/projects:/code/kaplancloudapp/projects
      - staticfiles:/code/staticfiles
    env_file:
      - .env
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST=db
      - DB_POST=5432
      - USE_GUNICORN=True
    depends_on:
      - db
    expose:
      - 8080
    restart: unless-stopped
  nginx:
    image: nginx
    container_name: ${PROJECT_NAME:-kaplan-cloud}_web
    env_file:
      - .env.web
    environment:
      - VIRTUAL_PORT=8080
    depends_on:
      - app
    networks:
      - default
      - customnetwork
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/staticfiles:ro
    expose:
      - 8080
    restart: unless-stopped
